### ISSUE TITLE
Startup output states

### ISSUE THREAD

**Issue by dougp2** [nerdralph/ArduinoShrink#1]
Thanks for making this library.  It does significantly reduce memory usage.

I tried ArduinoShrink on a short UNO program I was working on and found a bug.

Specifically, the program is a retriggerable/watchdog timer.  For an output indicator I used an external common anode LED to show when the input is being triggered.  Part of the idea is that the output should not be on unless and until the input is triggered and I included a boolean to keep the output off at startup/reset.

This works as desired without ArduinoShrink included.  When ArduinoShrink _is_ included the LED usually, but not always, gives one pulse at upload/reset. 

I don't know enough to contribute to a fix so I started this issue.  I also found the software won't let me attach an Arduino file.  If it's OK I can paste it in as text.

**Comment by nerdralph** [comment]
Are you using the v0.1.0, or did you pull from the master branch?  I'm working on v0.2.0, and pushing changes to master as I test different parts.
You could create a gist for your example code, and then include a link to it here.

**Comment by dougp2** [comment]
I'm using v0.1.0.  I'm a bit unsteady on the whole github thing but I did work out the gist.

Link to gist file [https://gist.github.com/dougp2/328b47d55c69f9e878216bc74feee3d1](url)

p.s.  Arduino IDE version 1.8.10, Win10

**Comment by nerdralph** [comment]
Looking at the code, I'd try `lastSignal = HIGH;` in setup().
https://gist.github.com/dougp2/328b47d55c69f9e878216bc74feee3d1#file-retriggerable_slash_watchdog_timer-L19

With ArduinoShrink your loop runs much faster, so the timing will be different.  In particular, the digitalRead() on line 19 could read low, because the ~35k pullup can take 1-2us to charge the parasitic capacitance of the AVR pin to the point where it reads HIGH.
For more details see this post I wrote: http://nerdralph.blogspot.com/2015/10/parasitic-capacitance-of-avr-mcu-pins.html

**Comment by dougp2** [comment]
> Looking at the code, I'd try lastSignal = HIGH; in setup().

Yep, that fixed it.  If digitalRead is left in place it also works to add a small delay, 5ms, just before - useful in the event the input state is unpredictable.  I'll be adding ArduinoShrink to my sketches.  

As an aside, Flash usage with my example is 2408 bytes standard, 1938 bytes with ArduinoShrink.  Impressive!

Thanks again!

**Comment by nerdralph** [comment]
OK, good to know it wasn't an ArduinoShrink bug.
p.s when I'm finished v0.2.0, that should save another 250-350 bytes.
